
package com.business.web.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ApplicationService", targetNamespace = "http://service.web.business.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ApplicationService {


    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessInfoQueryEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessInfoQueryEx", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessInfoQueryEx")
    @ResponseWrapper(localName = "BusinessInfoQueryExResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessInfoQueryExResponse")
    public String businessInfoQueryEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceSearchEx", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceSearchEx")
    @ResponseWrapper(localName = "businessLicenceSearchExResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceSearchExResponse")
    public List<String> businessLicenceSearchEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceExQuery", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceExQuery")
    @ResponseWrapper(localName = "businessLicenceExQueryResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceExQueryResponse")
    public String businessLicenceExQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceRegisterEx", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegisterEx")
    @ResponseWrapper(localName = "businessLicenceRegisterExResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegisterExResponse")
    public int businessLicenceRegisterEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceSearch", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceSearch")
    @ResponseWrapper(localName = "businessLicenceSearchResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceSearchResponse")
    public List<String> businessLicenceSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessLicenceUpdateQuery")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessLicenceUpdateQuery", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceUpdateQuery")
    @ResponseWrapper(localName = "BusinessLicenceUpdateQueryResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceUpdateQueryResponse")
    public String businessLicenceUpdateQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessLicenceInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessLicenceInfo", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceInfo")
    @ResponseWrapper(localName = "BusinessLicenceInfoResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceInfoResponse")
    public String businessLicenceInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessLicenceProQuery")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessLicenceProQuery", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceProQuery")
    @ResponseWrapper(localName = "BusinessLicenceProQueryResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceProQueryResponse")
    public String businessLicenceProQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.TestResponse")
    public int test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceRegisterInfoEx", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegisterInfoEx")
    @ResponseWrapper(localName = "businessLicenceRegisterInfoExResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegisterInfoExResponse")
    public int businessLicenceRegisterInfoEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessInfoQuery")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessInfoQuery", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessInfoQuery")
    @ResponseWrapper(localName = "BusinessInfoQueryResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessInfoQueryResponse")
    public String businessInfoQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BusinessLicenceState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessLicenceState", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceState")
    @ResponseWrapper(localName = "BusinessLicenceStateResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceStateResponse")
    public int businessLicenceState(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessCardOper", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessCardOper")
    @ResponseWrapper(localName = "businessCardOperResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessCardOperResponse")
    public String businessCardOper(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceRegister", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegister")
    @ResponseWrapper(localName = "businessLicenceRegisterResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceRegisterResponse")
    public int businessLicenceRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessLicenceUpdate", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceUpdate")
    @ResponseWrapper(localName = "businessLicenceUpdateResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceUpdateResponse")
    public int businessLicenceUpdate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "BusinessLicenceInfoEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BusinessLicenceInfoEx", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceInfoEx")
    @ResponseWrapper(localName = "BusinessLicenceInfoExResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessLicenceInfoExResponse")
    public String businessLicenceInfoEx(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessOperQuery", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessOperQuery")
    @ResponseWrapper(localName = "businessOperQueryResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessOperQueryResponse")
    public String businessOperQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "businessStatistics", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessStatistics")
    @ResponseWrapper(localName = "businessStatisticsResponse", targetNamespace = "http://service.web.business.com/", className = "com.business.web.service.BusinessStatisticsResponse")
    public String businessStatistics(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
