
package com.business.web.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApplicationServiceService", targetNamespace = "http://service.web.business.com/", wsdlLocation = "http://117.184.199.45:8082/businessLicenceService/services/AppService?wsdl")
public class ApplicationServiceService
    extends Service
{

    private final static URL APPLICATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException APPLICATIONSERVICESERVICE_EXCEPTION;
    private final static QName APPLICATIONSERVICESERVICE_QNAME = new QName("http://service.web.business.com/", "ApplicationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://117.184.199.45:8082/businessLicenceService/services/AppService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPLICATIONSERVICESERVICE_WSDL_LOCATION = url;
        APPLICATIONSERVICESERVICE_EXCEPTION = e;
    }

    public ApplicationServiceService() {
        super(__getWsdlLocation(), APPLICATIONSERVICESERVICE_QNAME);
    }

    public ApplicationServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPLICATIONSERVICESERVICE_QNAME, features);
    }

    public ApplicationServiceService(URL wsdlLocation) {
        super(wsdlLocation, APPLICATIONSERVICESERVICE_QNAME);
    }

    public ApplicationServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPLICATIONSERVICESERVICE_QNAME, features);
    }

    public ApplicationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public ApplicationService getApplicationServicePort() {
        return super.getPort(new QName("http://service.web.business.com/", "ApplicationServicePort"), ApplicationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ApplicationService
     */
    @WebEndpoint(name = "ApplicationServicePort")
    public ApplicationService getApplicationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.business.com/", "ApplicationServicePort"), ApplicationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPLICATIONSERVICESERVICE_EXCEPTION!= null) {
            throw APPLICATIONSERVICESERVICE_EXCEPTION;
        }
        return APPLICATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
